### ISSUE TITLE
sanic response cookie seems need type str rather than byte

### ISSUE THREAD

**Issue by yurenchen000** [sunset-developer/sanic-security#45]
**Describe the bug**
sanic response cookie seems need type str rather than bytes,
or got TypeError

// tested with sanic 20.12.3, 21.6.2

**To Reproduce**
server use `test/server.py`
client use curl:

//1. reg user //ok
```
curl -sv http://127.0.0.1:8000/api/test/auth/register -Femail=emailpass@register.com \
 -Fusername=test -Fpassword=testtest -Fverified=true
```
//2. login user // fail TypeError
// should login success
```
curl -sv http://127.0.0.1:8000/api/test/auth/login --user 'emailpass@register.com:testtest' -d ''
```

```
[2022-01-22 09:34:03 +0800] [1732395] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/api/test/auth/login'
Traceback (most recent call last):
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/server.py", line 509, in write_response
    response.output(
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/response.py", line 169, in output
    return self.get_headers(version, keep_alive, keep_alive_timeout, body)
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/response.py", line 64, in get_headers
    return format_http1_response(self.status, self.headers.items(), body)
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/headers.py", line 194, in format_http1_response
    headerbytes = format_http1(headers)
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/headers.py", line 184, in format_http1
    return "".join(f"{name}: {val}\r\n" for name, val in headers).encode()
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/headers.py", line 184, in <genexpr>
    return "".join(f"{name}: {val}\r\n" for name, val in headers).encode()
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/cookies.py", line 137, in __str__
    output = ["%s=%s" % (self.key, _quote(self.value))]
  File "/home/chen/.local/lib/python3.8/site-packages/sanic/cookies.py", line 30, in _quote
    if str is None or _is_legal_key(str):
TypeError: cannot use a string pattern on a bytes-like object
```

**Version**
// sanic-security         1.4.7

- sanic 20.12.3 + py3.8
- sanic 21.6.2 + py3.9

**Workaround**
seems in sanic 20.12.3, 21.6.2
response.cookie should be str type.

https://github.com/sunset-developer/sanic-security/blob/v1.4.7/sanic_security/models.py#L288

changes:
```diff
        response.cookies[cookie] = jwt.encode(
            payload, security_config.SECRET, security_config.SESSION_ENCODING_ALGORITHM
-        )
+        ).decode('utf-8')
```

**Comment by sunset-developer** [comment]
I'll look into it shortly.  If you'd like you can submit a pull request if you know how to fix the issue and I'll merge one I test.

**Comment by sunset-developer** [comment]
@yurenchen000 A new patch has been released that fixes this issue. You can upgrade via `pip3 install --upgrade sanic-security`. Thank you for bringing this to my attention. Feel free to create another issue if you have any more problems. :)
